### ISSUE TITLE
Guide slugs should be case-insensitive

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-bibliotheca-api#106]
Otherwise, some guides will be inserted and listed twice: 

![image](https://user-images.githubusercontent.com/677436/39646211-099fcce0-4fb1-11e8-99f2-fb121d9d47f4.png)

**Comment by rodri042** [comment]
I think they already are case-insensitive because the client [always sends lowercase strings](https://github.com/mumuki/mumuki-bibliotheca/blob/931f4779f22be647dcffc22563e798b2efd797ec/src/scripts/services/slug-service.js#L16) as slugs.

In the screenshots, the slugs are identical except for the organization ("mumukiproject" vs "mumuki project")

**Comment by flbulgarelli** [comment]
OK, you have a point. Buut here is another screenshot where you can see the problem: 

![image](https://user-images.githubusercontent.com/677436/39941330-9ae585d8-5532-11e8-89a7-a540035198f2.png)


Somehow we we are listing `Practica Procedimientos` twice. Also, there should't be organizations with spaces. Are we validating that?


> I think they already are case-insensitive because the client always sends lowercase strings as slugs.

Are they also being lower-cased when they are imported instead of created from scratch?

**Comment by rodri042** [comment]
> Are they also being lower-cased when they are imported instead of created from scratch?

Nope, it uses a `GuideBuilder` and save directly to the db. Anyway, the api should convert them all to lowercase at save, instead of trusting in whatever `mumuki-bibliotheca` sends. I did that in https://github.com/mumuki/mumuki-bibliotheca-api/pull/109

**Comment by flbulgarelli** [comment]
Fixed by last comment

**Comment by julian-berbel** [comment]
We had to revert #109 because it was causing inconsistencies between the slugs shown when doing a GET on `/guides` and the actual ones on the database which caused problems since mongo does not do case-insensitive searches. 

There was also the problem that when entering a topic or book, the slugs for lessons/chapters would keep their cases which caused further problems.

**Comment by flbulgarelli** [comment]
Related to https://github.com/mumuki/mumuki-bibliotheca-api/issues/113

**Comment by flbulgarelli** [comment]
I think that this issue may be completely unaddressable, since making all searches in all mongo queries  (classroom) and all sql queries (domain) case insensitive is too difficult. 

However, we may be still able to ensure that all - new - slugs are normalized before creation in the bibliotheca endpoints, using https://github.com/mumuki/mumukit-auth/pull/31. 

That way, we will still be able to keep case-sensitive searches for pre-6.5 release, but new content will be always normalized first. See #86

**Comment by flbulgarelli** [comment]
Closing because of last comment
